### testes da API



### autores

### criar autor 1
POST http://127.0.0.1:5000/autores
Content-Type: application/json

{
    "nome": "Machado de Assis",
    "nacionalidade": "Brasileira"
}

### criar autor 2
POST http://127.0.0.1:5000/autores
Content-Type: application/json

{
    "nome": "Dalton Trevisan",
    "nacionalidade": "Brasileira"
}

### criar autor sem livro
POST http://127.0.0.1:5000/autores
Content-Type: application/json

{
    "nome": "Autor Sem Livro",
    "nacionalidade": "Brasileira"
}

### tentar criar autor sem nome
POST http://127.0.0.1:5000/autores
Content-Type: application/json

{
    "nacionalidade": "Brasileira"
}

### listar todos os autores
GET http://127.0.0.1:5000/autores

### buscar autor pelo id
GET http://127.0.0.1:5000/autores/1

### buscar autor que não existe
GET http://127.0.0.1:5000/autores/999

### atualizar autor
PUT http://127.0.0.1:5000/autores/1
Content-Type: application/json

{
    "nome": "Machado de Assis",
    "nacionalidade": "Brasileiro"
}

### apagar autor
DELETE http://127.0.0.1:5000/autores/3


### livros

### Criar livro
POST http://127.0.0.1:5000/livros
Content-Type: application/json

{
    "titulo": "Dom Casmurro",
    "ano_publicacao": 1899,
    "autor_id": 1
}

### criar outro livro
POST http://127.0.0.1:5000/livros
Content-Type: application/json

{
    "titulo": "Grande Sertão",
    "ano_publicacao": 1997,
    "autor_id": 2
}

### tentar criar livro sem autro
POST http://127.0.0.1:5000/livros
Content-Type: application/json

{
    "titulo": "livro nenhum",
    "ano_publicacao": 2020,
    "autor_id": 999
}

### listar todos os livros
GET http://127.0.0.1:5000/livros

### buscar livro pelo id
GET http://127.0.0.1:5000/livros/1

### atualizar livro
PUT http://127.0.0.1:5000/livros/1
Content-Type: application/json

{
    "titulo": "Dom Casmurro",
    "ano_publicacao": 1900,
    "autor_id": 1
}

### apagar livro
DELETE http://127.0.0.1:5000/livros/2


### rotas especiais 

### JOIN livros com o nome do autor junto
GET http://127.0.0.1:5000/livros-completo

### filtro por caminho livros de um autor específico
GET http://127.0.0.1:5000/autores/1/livros

### busca por query string encontra dom casmurr
GET http://127.0.0.1:5000/livros/busca?titulo=dom

### busca por query string sem resultado
GET http://127.0.0.1:5000/livros/busca?titulo=xyz
